site_name: DiffBot Differential Drive Mobile Robot
theme:
  name: material
  highlightjs: true
  custom_dir: docs/custom_theme
  features:
    - navigation.tabs
    - navigation.top
#    - navigation.indexes
  palette:
    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

#extra_javascript:
#  - https://unpkg.com/mermaid@8.8.0/dist/mermaid.min.js
#  - custom_theme/js/config.js
  
repo_url: https://github.com/ros-mobile-robots/diffbot


edit_uri: https://github.com/ros-mobile-robots/ros-mobile-robots.github.io/tree/main/docs

# Extra parameters
extra:
  asset_dir: /resources # /assets
  diffbot_repo_url: https://github.com/ros-mobile-robots/diffbot/blob/noetic-devel
  remo_repo_url: https://github.com/ros-mobile-robots/remo_description/blob/main

markdown_extensions:
  - admonition
  - pymdownx.details
  - abbr
  - extra
  - footnotes
  - pymdownx.snippets
  - pymdownx.keys
  - pymdownx.highlight:
      linenums: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_div_format
  - pymdownx.arithmatex:
      generic: true

plugins:
  - search
  - macros
  - mkdocs-jupyter:
      execute: False
      include_source: True

nav:
  - Home: index.md
  - Components: components.md
  - Robotics Theory:
    - theory/index.md
    - Modeling and Control:
      - Introduction to Control Systems: theory/modeling-control/control-systems-introduction.md
      - Representations and models: theory/modeling-control/robot-representations.md
      - Modeling a Differential Drive Robot: theory/modeling-control/modeling-differential-drive-robot.md
      - Odometry: theory/modeling-control/odometry.md
    - Robot Vision: theory/robot-vision/overview.md
    - Object Detection: theory/object-detection/overview.md
    - State Estimation and Localization: theory/estimatione-localization/overview.md
    - Planning I: theory/planning1/overview.md
    - Planning II: theory/planning2/overview.md
    - Learning by Reinforcement: theory/reinforcement-learning/overview.md
    - Learning by Imitation: theory/imitation-learning/overview.md
  - Hardware and Theory:
    - Motion and Odometry: theory/motion-and-odometry.md
    - Power Supply: power-supply.md
    - Laser Range Scanner: laser-range-scanner.md
  - Processing Units:
    - Raspberry Pi Setup: rpi-setup.md
    - Jetson Nano Setup: jetson-nano-setup.md
    - Git Setup: git-setup.md
    - ROS Setup: ros-setup.md
    - Teensy MCU: teensy-mcu.md
    - Hardware Interfaces: hardware-interfaces.md
    - ROS Network Setup: ros-network-setup.md
  - Packages:
    - Packages: packages.md
    - Robot Package: diffbot_robot.md
    - Robot Description:
      - Robot Description: robot-description.md
      - Remo Description: packages/remo_description.md
    - Simulation: diffbot_gazebo.md
    - Control: diffbot_control.md
    - Base Hardware Interface: diffbot_base.md
    - Messages: diffbot_msgs.md
    - Motor Driver: grove_motor_driver.md
    - Motor and Encoder: DG01D-E-motor-with-encoder.md
    - Navigation: diffbot_navigation.md
    - SLAM: diffbot_slam.md
    - Move Base Flex: diffbot_mbf.md
    - Hardware Bringup: diffbot_bringup.md
    - Rasperry Pi Camera: packages/raspicam_node.md

google_analytics:
  - UA-117971961-1
  - auto
